Algoritmo "Cálculo da área do triângulo"
// Crie um algoritmo para calcular a área do triângulo, apresente o resultado.

Var

      BASE, ALTURA, AREA: REAL

Inicio
    ESCREVAL("CALCULE A ÁREA DO TRIÂNGULO")
    ESCREVAL("DIGITE O VALOR DA BASE")
    LEIA(BASE)
    ESCREVAL("DIGITE O VALOR DA ALTURA")
    LEIA(ALTURA)
    AREA<-(BASE*ALTURA)/2
    ESCREVAL("A ÁREA DO TRIÂNGULO É ", AREA)

Fimalgoritmo
