Algoritmo "Cálculo da área do retângulo"
// Desenvolva um algoritmo que receba a base e altura de um retângulo, calcule e mostre sua área.

Var

      BASE, ALTURA, AREA: REAL

Inicio
    ESCREVAL("CALCULE A ÁREA DO RETÂNGULO")
    ESCREVAL("DIGITE O VALOR DA BASE")
    LEIA(BASE)
    ESCREVAL("DIGITE O VALOR DA ALTURA")
    LEIA(ALTURA)
    AREA<-(BASE*ALTURA)/2
    ESCREVAL("A ÁREA DO RETÂNGULO É ", AREA)
Fimalgoritmo
